import React from 'react';
import {
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { languages } from '../constants/languages';
import { useLanguage } from '../i18n';
import { RootStackParamList } from '../navigation/AppNavigator';

export default function SettingsScreen() {
  const navigation =
    useNavigation<NativeStackNavigationProp<RootStackParamList>>();
  const { language } = useLanguage();
  const currentLanguage =
    languages.find((item) => item.code === language)?.label ?? 'English (US)';

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.headerRow}>
          <Pressable style={styles.iconButton}>
            <Icon name="menu" size={22} color="#0E5FB3" />
          </Pressable>
          <Text style={styles.brand}>EarlyEyes</Text>
          <Pressable style={styles.iconButton}>
            <Icon name="account-circle-outline" size={24} color="#0E5FB3" />
          </Pressable>
        </View>

        <Text style={styles.title}>Settings</Text>
        <Text style={styles.subtitle}>
          Manage your app preferences and review important information.
        </Text>

        <Pressable
          style={styles.card}
          onPress={() => navigation.navigate('LanguageSelect')}
        >
          <View style={[styles.cardIcon, styles.cardIconBlue]}>
            <Icon name="earth" size={18} color="#FFFFFF" />
          </View>
          <View style={styles.cardBody}>
            <Text style={styles.cardTitle}>Change Language</Text>
            <Text style={styles.cardSubtitle}>{currentLanguage}</Text>
          </View>
          <Icon name="chevron-right" size={22} color="#9CA3AF" />
        </Pressable>

        <Pressable style={styles.card}>
          <View style={[styles.cardIcon, styles.cardIconGreen]}>
            <Icon name="information" size={18} color="#1F2937" />
          </View>
          <View style={styles.cardBody}>
            <Text style={styles.cardTitle}>App Information</Text>
            <Text style={styles.cardSubtitle}>Version 2.4.1 (Build 890)</Text>
          </View>
          <Icon name="chevron-right" size={22} color="#9CA3AF" />
        </Pressable>

        <Pressable style={styles.card}>
          <View style={[styles.cardIcon, styles.cardIconGold]}>
            <Icon name="shield-account" size={18} color="#5B3B00" />
          </View>
          <View style={styles.cardBody}>
            <Text style={styles.cardTitle}>About EarlyEyes</Text>
            <Text style={styles.cardSubtitle}>
              Our mission and data privacy practices
            </Text>
          </View>
          <Icon name="chevron-right" size={22} color="#9CA3AF" />
        </Pressable>

        <View style={styles.disclaimerCard}>
          <View style={styles.disclaimerHeader}>
            <Icon name="alert" size={18} color="#B91C1C" />
            <Text style={styles.disclaimerTitle}>Medical Disclaimer</Text>
          </View>
          <Text style={styles.disclaimerText}>
            EarlyEyes is a screening tool, not a diagnostic device. The results
            provided by this application are intended solely to assist
            caregivers in identifying potential visual anomalies that may
            warrant further professional evaluation.
          </Text>
          <Text style={styles.disclaimerText}>
            This application does not replace the judgment, diagnosis, or
            treatment provided by a qualified pediatric ophthalmologist or
            general healthcare professional. Always consult a certified medical
            provider if you have any concerns regarding a child's health or
            vision, regardless of the results generated by EarlyEyes.
          </Text>
          <Text style={styles.disclaimerText}>
            In the event of a sudden change in vision, visible trauma to the
            eye, or any signs of acute distress, seek emergency medical
            assistance immediately. Do not rely on this application in
            emergency situations.
          </Text>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F5F3',
  },
  scrollContent: {
    padding: 24,
    gap: 16,
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EFECEA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brand: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0E5FB3',
  },
  title: {
    fontSize: 26,
    fontWeight: '800',
    color: '#1C1A19',
  },
  subtitle: {
    fontSize: 14,
    color: '#4B5563',
    lineHeight: 20,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D5DBE7',
  },
  cardIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardIconBlue: {
    backgroundColor: '#1D4ED8',
  },
  cardIconGreen: {
    backgroundColor: '#9BF28D',
  },
  cardIconGold: {
    backgroundColor: '#D9A441',
  },
  cardBody: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1F2937',
  },
  cardSubtitle: {
    marginTop: 4,
    fontSize: 12,
    color: '#6B7280',
  },
  disclaimerCard: {
    marginTop: 10,
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#FBD6CF',
    borderWidth: 1,
    borderColor: '#F4A3A3',
    gap: 10,
  },
  disclaimerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  disclaimerTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#B91C1C',
  },
  disclaimerText: {
    fontSize: 12,
    color: '#7F1D1D',
    lineHeight: 18,
  },
});
